import { defineConfig, type Plugin } from 'vite';
import react from '@vitejs/plugin-react';
import { createHash } from 'node:crypto';
import { readdirSync, statSync, writeFileSync, existsSync } from 'node:fs';
import { join, posix, relative, sep } from 'node:path';

/** Every file under `dir`, as paths relative to it, with forward slashes. */
function walk(dir: string, root = dir, out: string[] = []): string[] {
  if (!existsSync(dir)) return out;
  for (const entry of readdirSync(dir)) {
    const full = join(dir, entry);
    if (statSync(full).isDirectory()) walk(full, root, out);
    else out.push(relative(root, full).split(sep).join(posix.sep));
  }
  return out;
}

/**
 * The service worker: what makes Braillix survive a school's Wi-Fi.
 *
 * Written here rather than pulled in as a plugin dependency, because the whole thing is forty lines
 * and the alternative is a package whose behaviour we would have to learn anyway. It precaches the
 * app shell, the stylesheet, the fonts and — the part that matters — the Nemeth locale tables,
 * which is the difference between a maths engine and a maths engine that needs the internet.
 *
 * What it deliberately does NOT precache: the ONNX runtime and the handwriting model. Those are
 * ~150 MB, they are absent unless somebody ran `npm run fetch:model`, and a service worker that
 * tried to swallow them would turn the first visit into a download. They are cached at runtime if
 * they are ever fetched, which is the right time to decide.
 */
function serviceWorker(): Plugin {
  return {
    name: 'braillix-service-worker',
    apply: 'build',
    closeBundle() {
      const outDir = join(import.meta.dirname, 'dist');
      if (!existsSync(outDir)) return;

      const precache = walk(outDir).filter(
        (file) =>
          // The weights themselves are far too big to precache; the one-line file that says
          // whether they are here is not, and the recognition badge has to be right offline too.
          // (They still SHIP — the browser caches them on first use via the Cache API; precache
          // is only about what downloads before the app is usable at all.)
          (!file.startsWith('models/') || file === 'models/status.json') &&
          !file.startsWith('ort/') &&
          !file.startsWith('tesseract/') &&
          !file.endsWith('.wasm') &&
          !file.endsWith('.map') &&
          file !== 'sw.js',
      );

      // The cache name changes whenever any precached file changes, which is what makes an update
      // actually take effect rather than being served out of yesterday's cache forever.
      const version = createHash('sha256').update(precache.sort().join('|')).digest('hex').slice(0, 12);

      writeFileSync(
        join(outDir, 'sw.js'),
        `/* Generated by vite.config.ts — do not edit. Cache ${version}. */
const CACHE = 'braillix-${version}';
const PRECACHE = ${JSON.stringify(precache.map((file) => `./${file}`), null, 0)};

/*
 * ignoreVary, and the hour it cost.
 *
 * A static server sends "Vary: Origin". The Cache API honours Vary, so a stored response only
 * matches a request whose Origin header is the same as the one that fetched it. Precaching fetches
 * with no Origin header; the browser then asks for the same file as an ES MODULE, and module
 * requests are made in CORS mode, which sends one. Different Origin, no match, straight to the
 * network — which, offline, is the end of the app. index.html came back from the cache and the
 * script next to it did not, which is exactly as confusing as it sounds.
 *
 * Everything in this cache is our own static build, so Vary carries no information for us.
 */
const MATCH = { ignoreVary: true };

self.addEventListener('install', (event) => {
  event.waitUntil(
    caches.open(CACHE).then((cache) => cache.addAll(PRECACHE)).then(() => self.skipWaiting()),
  );
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches.keys()
      .then((names) => Promise.all(names.filter((name) => name !== CACHE).map((name) => caches.delete(name))))
      .then(() => self.clients.claim()),
  );
});

self.addEventListener('fetch', (event) => {
  const request = event.request;
  if (request.method !== 'GET') return;

  const url = new URL(request.url);
  if (url.origin !== self.location.origin) return; // a pod on the LAN is never cached

  // A navigation always gets the app shell: opening the installed app offline must not 404.
  if (request.mode === 'navigate') {
    event.respondWith(
      caches.match('./index.html', MATCH).then((cached) => cached || fetch(request)),
    );
    return;
  }

  event.respondWith(
    caches.match(request, MATCH).then((cached) => {
      if (cached) return cached;
      return fetch(request).then((response) => {
        // Cache what we successfully fetched, so the model and the runtime are there next time.
        if (response.ok && response.type === 'basic') {
          const copy = response.clone();
          caches.open(CACHE).then((cache) => cache.put(request, copy));
        }
        return response;
      });
    }),
  );
});
`,
        'utf8',
      );
      this.info?.(`service worker: ${precache.length} files precached (${version})`);
    },
  };
}

/*
 * v1 had a "slimForDeploy" plugin here that STRIPPED the recognition model and ONNX runtime
 * out of public builds. That policy is exactly how the founder met a dead scan button in
 * front of his team, and it is reversed for good (DECISIONS D-V2.12): the deployed artifact
 * carries everything its buttons promise, and assert-assets.mjs fails the build otherwise.
 * The service worker still precaches none of the big files — they download on first use and
 * are cached by the browser from then on.
 */

export default defineConfig({
  plugins: [react(), serviceWorker()],
  // Relative base so a built bundle runs from a file server, a subpath, or a USB stick.
  base: './',
  build: {
    target: 'es2022',
    rollupOptions: {
      external: [
        // Node-only backends of @huggingface/transformers. They must never reach the browser
        // bundle — they pull in `sharp` and `onnxruntime-node`, which are irrelevant here and
        // carry advisories. Guarded by a test in src/core/__tests__/bundle-hygiene.test.ts.
        'onnxruntime-node',
        'sharp',
      ],
    },
  },
  optimizeDeps: {
    exclude: ['onnxruntime-node', 'sharp'],
  },
  worker: {
    format: 'es',
  },
  server: {
    port: 5173,
    strictPort: false,
  },
});
