/**
 * Can Braillix carry the actual syllabus?
 *
 * Not "does Nemeth work" — that is `nemeth.test.ts`, against the published tables. This asks the
 * question a head teacher would ask: take the maths my school teaches, typed the way my teachers
 * type, and show me that all of it reaches the display. Seventy lines, from a single digit to a
 * definite integral, plus word problems in both languages.
 *
 * When this file writes `docs/ACCURACY.md` (via `npm run accuracy`) it is producing evidence rather
 * than decoration: the same list, with what each line actually became, so a panel can check a cell
 * against a published table without running anything.
 */

import { beforeAll, describe, expect, it } from 'vitest';
import { writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { initSre } from './sre-service';
import { toLatex } from './mathinput';
import { translateMixed } from './mixed';
import { cellsToUnicode } from './translate';
import { SYLLABUS, allEntries } from './syllabus';

beforeAll(async () => {
  const status = await initSre();
  expect(status.ok, `speech-rule-engine failed to start: ${status.reason ?? ''}`).toBe(true);
}, 60_000);

interface Outcome {
  topic: string;
  source: string;
  says: string;
  latex: string;
  braille: string;
  cells: number;
  issues: string[];
}

const outcomes: Outcome[] = [];

describe('the school syllabus reaches the display', () => {
  for (const topic of SYLLABUS) {
    describe(topic.topic, () => {
      for (const entry of topic.entries) {
        it(`${entry.source}  (${entry.says})`, async () => {
          const line = await translateMixed(entry.source);
          const issues = line.segments.flatMap((segment) => segment.issues);

          outcomes.push({
            topic: topic.topic,
            source: entry.source,
            says: entry.says,
            latex: line.segments.map((segment) => segment.latex || segment.text).join(' '),
            braille: cellsToUnicode(line.cells),
            cells: line.cells.length,
            issues: issues.map((issue) => `${issue.kind}: ${issue.message}`),
          });

          // 1. Something reached the cells.
          expect(line.cells.length, 'produced no braille at all').toBeGreaterThan(0);
          // 2. Nothing was quietly skipped.
          expect(
            issues.filter((issue) => issue.kind !== 'engine').map((issue) => issue.message),
            'a character or a parse was lost',
          ).toEqual([]);
          // 3. The natural input and the LaTeX it becomes are the same maths.
          if (!line.mixed) {
            const direct = toLatex(entry.source).latex;
            expect(direct.length, 'the input parser produced nothing').toBeGreaterThan(0);
          }
        });
      }
    });
  }

  it('covers a wide enough surface to mean anything', () => {
    expect(allEntries().length).toBeGreaterThanOrEqual(60);
    expect(SYLLABUS.length).toBeGreaterThanOrEqual(8);
  });

  /**
   * Written only when asked (`npm run accuracy`), so an ordinary test run never dirties the tree.
   */
  it('writes the evidence when asked', () => {
    if (!process.env.BRAILLIX_WRITE_ACCURACY) return;

    const path = join(import.meta.dirname, '..', '..', '..', 'docs', 'ACCURACY.md');
    mkdirSync(dirname(path), { recursive: true });

    const failures = outcomes.filter((outcome) => outcome.issues.length > 0);
    const lines: string[] = [
      '# What Braillix can carry',
      '',
      'Generated by `npm run accuracy`. Every line below is written the way a teacher writes it on',
      'the Board, translated by the same code that drives the display, and shown as the braille that',
      'reaches the cells. Nothing here is hand-typed.',
      '',
      `**${outcomes.length} lines across ${SYLLABUS.length} topics. ${outcomes.length - failures.length} translated cleanly, ${failures.length} with something to report.**`,
      '',
      'Read a cell against a published Nemeth table and it should agree. If it does not, that is a',
      'bug worth reporting, and this file is where to look for it.',
      '',
    ];

    for (const topic of SYLLABUS) {
      const rows = outcomes.filter((outcome) => outcome.topic === topic.topic);
      if (rows.length === 0) continue;
      lines.push(`## ${topic.topic}  ·  classes ${topic.classes}`, '');
      lines.push('| Typed | Means | Braille | Cells |', '|---|---|---|---|');
      for (const row of rows) {
        const note = row.issues.length ? ` ⚠ ${row.issues.join('; ')}` : '';
        lines.push(
          `| \`${row.source}\` | ${row.says} | ${row.braille}${note} | ${row.cells} |`,
        );
      }
      lines.push('');
    }

    writeFileSync(path, lines.join('\n'), 'utf8');
    expect(outcomes.length).toBeGreaterThan(0);
  });
});
